# Generated by Django 3.1.7 on 2021-03-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('games', 'games'), ('tech', 'tech'), ('meme', 'meme'), ('crypyo', 'crypto'), ('outros', 'outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
