# Generated by Django 3.1.7 on 2021-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210309_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='perfil'),
        ),
    ]
